#ifndef L0L2_VERSION_HPP
#define L0L2_VERSION_HPP

#define L0L2_STRINGIFY(x) #x
#define L0L2_MACRO_STRINGIFY(x) L0L2_STRINGIFY(x)

#define L0L2_VERSION_MAJOR 0
#define L0L2_VERSION_MINOR 1
#define L0L2_VERSION_PATCH 0

#define L0L2_VERSION L0L2_VERSION_MAJOR.L0L2_VERSION_MINOR.L0L2_VERSION_PATCH

#endif //L0L2_VERSION_HPP
